[package]
name = "browser-history"
version = "0.1.0"
edition = "2021"

[lib]
name = "browser_history"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.24"
log = "0.4.17"
rusqlite = "0.29.0"
rust-ini = "0.18.0"
uuid = { version = "1.3.0", features = ["v4", "fast-rng","macro-diagnostics"] }
